services:
  - type: web
    name: myproject
    env: python
    plan: free
    buildCommand: "python manage.py collectstatic --noinput"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings